# Generated by Django 4.1.3 on 2022-12-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_decisiontreenode_remove_genre_parent_delete_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisiontreenode',
            name='moreThanTwo_node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moreThanTwo_nodes', to='questions.decisiontreenode'),
        ),
        migrations.AddField(
            model_name='decisiontreenode',
            name='one_node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_nodes', to='questions.decisiontreenode'),
        ),
        migrations.AddField(
            model_name='decisiontreenode',
            name='two_node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_nodes', to='questions.decisiontreenode'),
        ),
    ]
