# Generated by Django 4.2.4 on 2023-11-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_remove_datafile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='test_stat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
