# Generated by Django 4.2.4 on 2023-11-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_datafile_test_stat_alter_datafile_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='ended',
            field=models.IntegerField(default=1),
        ),
    ]
